---
apiVersion: v1
kind: ConfigMap
metadata:
  name: advanced-risk-config
  namespace: crypto-trading
  labels:
    app: advanced-risk-service
data:
  DATABASE_HOST: "host.docker.internal"
  DATABASE_USER: "news_collector"
  DATABASE_NAME: "crypto_prices"
  DATABASE_PORT: "3306"
  LOG_LEVEL: "INFO"
  PROMETHEUS_METRICS_ENABLED: "true"
  METRICS_PORT: "9091"
  MAX_PORTFOLIO_HEAT: "0.25"
  VOLATILITY_LOOKBACK_DAYS: "30"
  CORRELATION_THRESHOLD: "0.7"

---
apiVersion: v1
kind: Secret
metadata:
  name: advanced-risk-secrets
  namespace: crypto-trading
  labels:
    app: advanced-risk-service
type: Opaque
stringData:
  DATABASE_PASSWORD: "99Rules!"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: advanced-risk-service
  namespace: crypto-trading
  labels:
    app: advanced-risk-service
    component: risk-management
    version: v1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: advanced-risk-service
  template:
    metadata:
      labels:
        app: advanced-risk-service
        component: risk-management
        version: v1.0.0
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9091"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: advanced-risk-service
        image: aitest-advanced-risk-service:latest
        imagePullPolicy: Never  # For local development
        ports:
        - containerPort: 8027
          name: http
          protocol: TCP
        - containerPort: 9091
          name: metrics
          protocol: TCP
        env:
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: advanced-risk-secrets
              key: DATABASE_PASSWORD
        envFrom:
        - configMapRef:
            name: advanced-risk-config
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8027
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8027
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8027
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 10

---
apiVersion: v1
kind: Service
metadata:
  name: advanced-risk-service
  namespace: crypto-trading
  labels:
    app: advanced-risk-service
    component: risk-management
spec:
  type: ClusterIP
  selector:
    app: advanced-risk-service
  ports:
  - name: http
    port: 8027
    targetPort: 8027
    protocol: TCP
  - name: metrics
    port: 9091
    targetPort: 9091
    protocol: TCP