apiVersion: apps/v1
kind: Deployment
metadata:
  name: enhanced-signal-generator
  namespace: crypto-trading
  labels:
    app: enhanced-signal-generator
    component: signal-generation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enhanced-signal-generator
  template:
    metadata:
      labels:
        app: enhanced-signal-generator
        component: signal-generation
    spec:
      containers:
      - name: enhanced-signal-generator
        image: aitest-enhanced-signal-generator:with-original-model
        imagePullPolicy: Never
        ports:
        - containerPort: 8025
          name: http
        env:
        - name: DB_HOST
          value: "172.22.32.1"
        - name: DB_USER
          value: "news_collector"
        - name: DB_PASSWORD
          value: "99Rules!"
        - name: DB_NAME
          value: "crypto_prices"
        - name: REDIS_HOST
          value: "infra-redis"
        - name: REDIS_PORT
          value: "6379"
        - name: SIGNAL_GENERATION_INTERVAL
          value: "300"  # 5 minutes - back to frequent generation
        - name: MARKET_HOURS_INTERVAL
          value: "300"  # 5 minutes during active hours  
        - name: QUIET_HOURS_INTERVAL
          value: "600"  # 10 minutes during quiet hours
        - name: SIGNAL_BATCH_SIZE
          value: "25"  # Process 25 assets per batch
        - name: ML_MODEL_PATH
          value: "/app/full_dataset_gpu_xgboost_model_20250827_130225.joblib"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8025
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8025
          initialDelaySeconds: 10
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: enhanced-signal-generator
  namespace: crypto-trading
  labels:
    app: enhanced-signal-generator
    component: signal-generation
spec:
  selector:
    app: enhanced-signal-generator
  ports:
  - port: 8025
    targetPort: 8025
    protocol: TCP
    name: http
  type: ClusterIP
