apiVersion: v1
kind: Service
metadata:
  name: trade-exec-coinbase
  namespace: crypto-trading
  labels:
    app: trade-exec-coinbase
    category: trade-execution
    component: coinbase
spec:
  type: ExternalName
  externalName: host.docker.internal
  ports:
  - port: 8024
    targetPort: 8024
    protocol: TCP
    name: http