apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservices-signal-bridge
  namespace: crypto-trading
  labels:
    app: microservices-signal-bridge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservices-signal-bridge
  template:
    metadata:
      labels:
        app: microservices-signal-bridge
    spec:
      containers:
      - name: microservices-signal-bridge
        image: aitest-enhanced-signal-bridge:v12-env-dynamic-size
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: signal-proc-bridge-config
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8022
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8022
          initialDelaySeconds: 10
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: microservices-signal-bridge
  namespace: crypto-trading
  labels:
    app: microservices-signal-bridge
spec:
  selector:
    app: microservices-signal-bridge
  ports:
  - port: 8022
    targetPort: 8022
    name: http
