apiVersion: apps/v1
kind: Deployment
metadata:
  name: minimal-trade-proxy
  namespace: crypto-trading
  labels:
    app: minimal-trade-proxy
    category: trade-execution
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minimal-trade-proxy
  template:
    metadata:
      labels:
        app: minimal-trade-proxy
        category: trade-execution
    spec:
      containers:
      - name: minimal-trade-proxy
        image: aitest-minimal-trade-exec:fixed
        imagePullPolicy: Never
        ports:
        - containerPort: 8024
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "50m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8024
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8024
          initialDelaySeconds: 10
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: trade-exec-minimal
  namespace: crypto-trading
  labels:
    app: minimal-trade-proxy
spec:
  type: NodePort
  ports:
  - port: 8024
    targetPort: 8024
    nodePort: 30024
    protocol: TCP
  selector:
    app: minimal-trade-proxy