apiVersion: apps/v1
kind: Deployment
metadata:
  name: minimal-trade-exec
  namespace: crypto-collectors
  labels:
    app: minimal-trade-exec
    category: trading
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minimal-trade-exec
  template:
    metadata:
      labels:
        app: minimal-trade-exec
        category: trading
    spec:
      containers:
      - name: minimal-trade-exec
        image: aitest-minimal-trade-exec:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8024
          name: http
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "64Mi"
            cpu: "50m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8024
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8024
          initialDelaySeconds: 5
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: minimal-trade-exec
  namespace: crypto-collectors
  labels:
    app: minimal-trade-exec
    category: trading
spec:
  type: NodePort
  ports:
  - port: 8024
    targetPort: 8024
    nodePort: 30024
    protocol: TCP
    name: http
  selector:
    app: minimal-trade-exec