apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-prediction
  namespace: crypto-trading
  labels:
    app: ml-prediction
    component: ml-analytics
    version: v1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-prediction
  template:
    metadata:
      labels:
        app: ml-prediction
        component: ml-analytics
        version: v1.0.0
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8040"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: ml-prediction
        image: aitest-ml-prediction:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 9092
          name: metrics
        env:
        - name: DATABASE_HOST
          value: "host.docker.internal"
        - name: DATABASE_USER
          value: "news_collector"
        - name: DATABASE_PASSWORD
          value: "99Rules!"
        - name: DATABASE_NAME
          value: "crypto_prices"
        - name: AWS_REGION
          value: "us-west-2"
        - name: MODEL_CACHE_SIZE
          value: "30"
        - name: PREDICTION_CACHE_TTL
          value: "300"
        - name: ENABLE_MODEL_RETRAINING
          value: "true"
        - name: METRICS_PORT
          value: "9092"
        - name: LOG_LEVEL
          value: "INFO"
        - name: PROMETHEUS_METRICS_ENABLED
          value: "true"
        - name: MIN_CONFIDENCE_THRESHOLD
          value: "0.65"
        - name: MODEL_UPDATE_INTERVAL_HOURS
          value: "24"
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 20
        volumeMounts:
        - name: model-cache
          mountPath: /models
      volumes:
      - name: model-cache
        emptyDir:
          sizeLimit: "2Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: ml-prediction
  namespace: crypto-trading
  labels:
    app: ml-prediction
    component: ml-analytics
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9092"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: ml-prediction
  ports:
  - name: http
    port: 8040
    targetPort: 8000
    protocol: TCP
  - name: metrics
    port: 9092
    targetPort: 9092
    protocol: TCP
  type: ClusterIP
