apiVersion: v1
kind: ConfigMap
metadata:
  name: ollama-config
  namespace: crypto-trading
  labels:
    app: ollama
    component: llm-config
data:
  # Ollama Server Configuration
  OLLAMA_HOST: "0.0.0.0"
  OLLAMA_ORIGINS: "*"
  OLLAMA_MODELS_PATH: "/root/.ollama/models"
  
  # LLM Model Configuration
  DEFAULT_MODEL: "llama3.2:3b"
  MODEL_DOWNLOAD_TIMEOUT: "300"
  MODEL_INFERENCE_TIMEOUT: "60"
  
  # Service URLs
  OLLAMA_SERVER_URL: "http://ollama:11434"
  LLM_VALIDATION_URL: "http://ollama-llm-validation:8050"
  
  # Validation Settings
  VALIDATION_ENABLED: "true"
  CONFIDENCE_THRESHOLD: "0.7"
  MAX_VALIDATION_TIME: "30"
