apiVersion: v1
kind: ConfigMap
metadata:
  name: optimized-signal-config
  namespace: crypto-trading
data:
  signal_generation.env: |
    # Optimized Signal Generation Parameters
    SIGNAL_GENERATION_INTERVAL=600
    MIN_ML_CONFIDENCE=0.7
    MIN_FALLBACK_CONFIDENCE=0.75
    FEATURE_IMPORTANCE_THRESHOLD=0.01
    
  signal_bridge.env: |
    # Optimized Signal Bridge Parameters  
    HIGH_CONFIDENCE_COOLDOWN=120
    MEDIUM_CONFIDENCE_COOLDOWN=240
    LOW_CONFIDENCE_COOLDOWN=360
    CONFIDENCE_BASED_SIZING=true
    MIN_CONFIDENCE_FOR_LARGE_TRADES=0.85
    
  market_conditions.env: |
    # Market Condition Awareness
    LOW_VOLATILITY_MULTIPLIER=1.5
    HIGH_VOLATILITY_MULTIPLIER=0.75
    VOLATILITY_THRESHOLD=0.02
    CORRELATION_CHECK_ENABLED=true
    MAX_CORRELATED_POSITIONS=3
    
  monitoring.env: |
    # Enhanced Monitoring Parameters
    MAX_SIGNALS_PER_HOUR=30
    MAX_TRADES_PER_HOUR=15
    CONFIDENCE_DEGRADATION_THRESHOLD=0.05
    MODEL_VARIANCE_THRESHOLD=0.3
    
  llm_integration.env: |
    # LLM Integration Enhancements
    CONFIDENCE_BOOST_FOR_LLM_AGREEMENT=0.1
    LLM_VETO_THRESHOLD=0.2
    MARKET_SENTIMENT_WEIGHT=0.15
    INCLUDE_RECENT_NEWS=true
    INCLUDE_SOCIAL_SENTIMENT=true
    INCLUDE_MACRO_INDICATORS=true

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: enhanced-anti-churn-config
  namespace: crypto-trading
data:
  anti_churn_rules.json: |
    {
      "confidence_based_cooldowns": {
        "very_high": {"min_confidence": 0.9, "cooldown_minutes": 120},
        "high": {"min_confidence": 0.85, "cooldown_minutes": 180},
        "medium_high": {"min_confidence": 0.8, "cooldown_minutes": 240},
        "minimum": {"min_confidence": 0.75, "cooldown_minutes": 360}
      },
      "market_condition_adjustments": {
        "low_volatility": {"multiplier": 1.5, "threshold": 0.01},
        "high_volatility": {"multiplier": 0.75, "threshold": 0.04}
      },
      "correlation_limits": {
        "max_correlated_positions": 3,
        "correlation_threshold": 0.7,
        "correlation_groups": [
          ["BTC", "ETH", "ADA", "DOT"],
          ["LINK", "UNI", "AAVE", "SUSHI"],
          ["LTC", "BCH", "XRP", "XLM"],
          ["SOL", "AVAX", "MATIC", "FTM"]
        ]
      },
      "position_sizing": {
        "confidence_based": true,
        "base_size_usd": 25,
        "max_size_multiplier": 1.5,
        "large_trade_threshold": 50,
        "min_confidence_for_large": 0.85
      },
      "emergency_brakes": {
        "max_trades_per_hour": 15,
        "max_loss_per_day": 100,
        "consecutive_loss_limit": 3,
        "pause_trading_on_breach": true
      }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: enhanced-signal-generator-optimized
  namespace: crypto-trading
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enhanced-signal-generator-optimized
  template:
    metadata:
      labels:
        app: enhanced-signal-generator-optimized
    spec:
      containers:
      - name: signal-generator
        image: signal-generator:optimized-v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8025
        env:
        - name: SIGNAL_GENERATION_INTERVAL
          valueFrom:
            configMapKeyRef:
              name: optimized-signal-config
              key: SIGNAL_GENERATION_INTERVAL
        - name: MIN_ML_CONFIDENCE
          valueFrom:
            configMapKeyRef:
              name: optimized-signal-config
              key: MIN_ML_CONFIDENCE
        envFrom:
        - configMapRef:
            name: optimized-signal-config
        volumeMounts:
        - name: ml-model
          mountPath: /app/full_dataset_gpu_xgboost_model_20250827_130225.joblib
          subPath: full_dataset_gpu_xgboost_model_20250827_130225.joblib
        - name: anti-churn-config
          mountPath: /app/config
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi" 
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8025
          initialDelaySeconds: 30
          periodSeconds: 60
        readinessProbe:
          httpGet:
            path: /health
            port: 8025
          initialDelaySeconds: 10
          periodSeconds: 30
      volumes:
      - name: ml-model
        hostPath:
          path: /path/to/model  # Will be mounted from host
      - name: anti-churn-config
        configMap:
          name: enhanced-anti-churn-config

---
apiVersion: v1
kind: Service
metadata:
  name: enhanced-signal-generator-optimized
  namespace: crypto-trading
spec:
  selector:
    app: enhanced-signal-generator-optimized
  ports:
  - name: http
    port: 8025
    targetPort: 8025
  type: ClusterIP