apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-optimization
  namespace: crypto-trading
  labels:
    app: portfolio-optimization
    component: trading
    version: v1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-optimization
  template:
    metadata:
      labels:
        app: portfolio-optimization
        component: trading
        version: v1.0.0
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8026"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: portfolio-optimization
        image: aitest-portfolio-optimization:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8026
          name: http
        - containerPort: 9090
          name: metrics
        env:
        - name: DATABASE_HOST
          value: "host.docker.internal"
        - name: DATABASE_USER
          value: "news_collector"
        - name: DATABASE_PASSWORD
          value: "99Rules!"
        - name: DATABASE_NAME_TRANSACTIONS
          value: "crypto_transactions"
        - name: DATABASE_NAME_PRICES
          value: "crypto_prices"
        - name: DATABASE_PORT
          value: "3306"
        - name: TRADING_ENGINE_URL
          value: "http://trade-exec-coinbase:8024"
        - name: MIN_POSITION_SIZE
          value: "50.0"
        - name: MAX_POSITIONS
          value: "15"
        - name: REBALANCE_THRESHOLD
          value: "0.20"
        - name: METRICS_PORT
          value: "9090"
        - name: LOG_LEVEL
          value: "INFO"
        - name: PROMETHEUS_METRICS_ENABLED
          value: "true"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8026
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8026
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8026
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-optimization
  namespace: crypto-trading
  labels:
    app: portfolio-optimization
    component: trading
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: portfolio-optimization
  ports:
  - name: http
    port: 8026
    targetPort: 8026
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  type: ClusterIP
