apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-performance-feedback
  namespace: crypto-trading
  labels:
    app: trading-performance-feedback
    component: performance-analytics
    version: v1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trading-performance-feedback
  template:
    metadata:
      labels:
        app: trading-performance-feedback
        component: performance-analytics
        version: v1.0.0
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8051"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: trading-performance-feedback
        image: aitest-trading-performance-feedback:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8031
          name: http
        - containerPort: 9095
          name: metrics
        env:
        - name: DATABASE_HOST
          value: "host.docker.internal"
        - name: DATABASE_USER
          value: "news_collector"
        - name: DATABASE_PASSWORD
          value: "99Rules!"
        - name: DATABASE_NAME
          value: "crypto_prices"
        - name: TRADES_DATABASE
          value: "crypto_transactions"
        - name: ANALYTICS_INTERVAL_MINUTES
          value: "15"
        - name: PERFORMANCE_LOOKBACK_DAYS
          value: "7"
        - name: ENABLE_REAL_TIME_ANALYTICS
          value: "true"
        - name: METRICS_PORT
          value: "9095"
        - name: LOG_LEVEL
          value: "INFO"
        - name: PROMETHEUS_METRICS_ENABLED
          value: "true"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8031
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8031
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8031
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: trading-performance-feedback
  namespace: crypto-trading
  labels:
    app: trading-performance-feedback
    component: performance-analytics
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9095"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: trading-performance-feedback
  ports:
  - name: http
    port: 8051
    targetPort: 8031
    protocol: TCP
  - name: metrics
    port: 9095
    targetPort: 9095
    protocol: TCP
  type: ClusterIP
