apiVersion: v1
kind: ConfigMap
metadata:
  name: trade-proc-orchestrator-config
  namespace: crypto-trading
  labels:
    app: trade-proc-orchestrator
    category: trade-processing
    component: orchestrator
data:
  # Service URLs (using new K8s service names)
  RECOMMENDATION_SERVICE_URL: "http://signal-proc-bridge:8022"
  EXECUTION_SERVICE_URL: "http://trade-exec-coinbase:8024"
  
  # Trading Configuration
  MAX_AGE_HOURS: "4"
  CHECK_INTERVAL: "30"
  MAX_TRADES_PER_CYCLE: "3"
  
  # Logging
  LOG_LEVEL: "INFO"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trade-proc-orchestrator
  namespace: crypto-trading
  labels:
    app: trade-proc-orchestrator
    category: trade-processing
    component: orchestrator
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trade-proc-orchestrator
  template:
    metadata:
      labels:
        app: trade-proc-orchestrator
        category: trade-processing
        component: orchestrator
        version: v1
    spec:
      containers:
      - name: trade-proc-orchestrator
        image: aitest-automated-live-trader:fixed-v1
        command: ["python", "automated_live_trader.py"]
        imagePullPolicy: Never  # For local development
        ports:
        - containerPort: 8023
          name: http
          protocol: TCP
        envFrom:
        - configMapRef:
            name: trade-proc-orchestrator-config
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8023
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8023
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: logs
        emptyDir: {}
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: trade-proc-orchestrator
  namespace: crypto-trading
  labels:
    app: trade-proc-orchestrator
    category: trade-processing
    component: orchestrator
spec:
  type: ClusterIP
  ports:
  - port: 8023
    targetPort: 8023
    protocol: TCP
    name: http
  selector:
    app: trade-proc-orchestrator