apiVersion: v1
kind: Namespace
metadata:
  name: crypto-trading
  labels:
    name: crypto-trading
    monitoring: enabled
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: signal-gen-config
  namespace: crypto-trading
data:
  MYSQL_HOST: "mysql.crypto-trading.svc.cluster.local"
  MYSQL_USER: "news_collector"
  MYSQL_DATABASE: "crypto_prices"
  LOG_LEVEL: "INFO"
  PYTHONUNBUFFERED: "1"
---
apiVersion: v1
kind: Secret
metadata:
  name: signal-gen-secrets
  namespace: crypto-trading
type: Opaque
stringData:
  MYSQL_PASSWORD: "99Rules!"
---
apiVersion: v1
kind: Service
metadata:
  name: signal-gen-orchestrator
  namespace: crypto-trading
  labels:
    app: signal-gen-orchestrator
    service: orchestrator
spec:
  selector:
    app: signal-gen-orchestrator
  ports:
  - name: http
    port: 8025
    targetPort: 8025
  - name: metrics
    port: 9090
    targetPort: 8025
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: signal-gen-orchestrator
  namespace: crypto-trading
  labels:
    app: signal-gen-orchestrator
    service: orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: signal-gen-orchestrator
  template:
    metadata:
      labels:
        app: signal-gen-orchestrator
        service: orchestrator
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8025"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: orchestrator
        image: signal-gen-orchestrator:v4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8025
          name: http
        env:
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: signal-gen-config
              key: MYSQL_HOST
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: signal-gen-config
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: signal-gen-secrets
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: signal-gen-config
              key: MYSQL_DATABASE
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: signal-gen-config
              key: LOG_LEVEL
        - name: PYTHONUNBUFFERED
          valueFrom:
            configMapKeyRef:
              name: signal-gen-config
              key: PYTHONUNBUFFERED
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8025
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8025
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: logs
        emptyDir: {}
      restartPolicy: Always