apiVersion: v1
kind: ServiceMonitor
metadata:
  name: signal-generation-services
  namespace: crypto-trading
  labels:
    app: signal-generation
    monitoring: prometheus
spec:
  selector:
    matchLabels:
      service: orchestrator
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
---
apiVersion: v1
kind: ServiceMonitor
metadata:
  name: signal-generation-ml-engine
  namespace: crypto-trading
  labels:
    app: signal-generation
    monitoring: prometheus
spec:
  selector:
    matchLabels:
      service: ml-engine
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
---
apiVersion: v1
kind: ServiceMonitor
metadata:
  name: signal-generation-feature-engine
  namespace: crypto-trading
  labels:
    app: signal-generation
    monitoring: prometheus
spec:
  selector:
    matchLabels:
      service: feature-engine
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
---
apiVersion: v1
kind: ServiceMonitor
metadata:
  name: signal-generation-market-context
  namespace: crypto-trading
  labels:
    app: signal-generation
    monitoring: prometheus
spec:
  selector:
    matchLabels:
      service: market-context
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
---
apiVersion: v1
kind: ServiceMonitor
metadata:
  name: signal-generation-portfolio
  namespace: crypto-trading
  labels:
    app: signal-generation
    monitoring: prometheus
spec:
  selector:
    matchLabels:
      service: portfolio
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
---
apiVersion: v1
kind: ServiceMonitor
metadata:
  name: signal-generation-risk-mgmt
  namespace: crypto-trading
  labels:
    app: signal-generation
    monitoring: prometheus
spec:
  selector:
    matchLabels:
      service: risk-mgmt
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
---
apiVersion: v1
kind: ServiceMonitor
metadata:
  name: signal-generation-analytics
  namespace: crypto-trading
  labels:
    app: signal-generation
    monitoring: prometheus
spec:
  selector:
    matchLabels:
      service: analytics
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s