apiVersion: v1
kind: Service
metadata:
  name: coinbase-listing-trader
  namespace: crypto-trading
  labels:
    app: coinbase-listing-trader
    component: signal-generation
    service-type: listing-detection
spec:
  selector:
    app: coinbase-listing-trader
  ports:
  - name: http
    port: 8033
    targetPort: 8033
    protocol: TCP
  type: ClusterIP